spring:
    application:
        name: gateway-app
    zipkin:
        baseUrl: http://localhost:9411
server:
    port: 8080

# Zuul config
zuul:
    routes:
        time:
            path: /api/time/**
            serviceId: time-service
        greeting:
            path: /api/greeting/**
            serviceId: greeting-service
 #register new services here
#
#eureka:
#    client:
#        registerWithEureka: false
