spring:
  application:
    name: gateway-app
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: app-gateway
server:
  port: 8080

