spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: greeting-service

server:
  port: 0