spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:8082/realms/spring-cloud-ms-ex
        registration:
          oidc:
            client-id: greeting-service
            client-secret: secret123
            scope: openid, profile, email, offline_access # last one for refresh tokens

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    jms:
      enabled: true

logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
server:
  port: 0

springdoc:
  api-docs:
    resolve-schema-properties: false
  show-actuator: true
  swagger-ui:
    try-it-out-enabled: false
  writer-with-order-by-keys: true