spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


server:
  port: 0

springdoc:
  api-docs:
    resolve-schema-properties: false
  show-actuator: true
  swagger-ui:
    try-it-out-enabled: false
  writer-with-order-by-keys: true