# this should serve as base config file for all apps

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"