server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream # it allows to monitor the stream  http://localhost:8080/actuator/hystrix.stream