

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/spring-boot-microservice-example-java/configs/local
  profiles:
    active: native
